### PR TITLE
Add an alias for compiling with warnings-as-errors

### PR DESCRIPTION
**Pull request by rafal0p**
I added this locally, why not to push it to upstream.

### CODE REVIEW

**Review by gusaiani — APPROVED** [review]
Thanks @rafal0p.

By the way, over recent years I haven't been doing much Elixir unfortunately.

If you'd like to become an admin for this repo, please let me know and I'll push the buttons.

**Comment by rafal0p** [comment]
Sure, go ahead. Where do I sign? ;)

**Comment by gusaiani** [comment]
> Sure, go ahead. Where do I sign? ;)

Invite sent just now. Thank you :)

**Comment by rafal0p** [comment]
Cheers!

**Pull request merged**
